version: '2.1'

services:
  rails:
    build: .
    image: rails
    container_name: rails
    volumes:
      - "data_work:/home/ubuntu/work"
    ports:
      - "22:22"
      - "5901:5901"
      - "3000:3000"
    network_mode: "host"

volumes:
  data_work:
