version: '2.1'

services:
  rails:
    build: .
    image: rails
    container_name: rails
    volumes:
      - "data_work:/home/ubuntu"
      - "/home/demers/share:/home/ubuntu/share"
      - "/dev/shm:/dev/shm"
    ports:
      - "22:22"
      - "6080:80"
      - "5900:5900"
      - "3000:3000"
    network_mode: "host"

volumes:
  data_work:
